next/.eslintrc.json, next/package-lock.json, next/package.json
Adds eslint plugin for tailwind to enforce class name order and detect if classes can be merged
=> Adds Tailwind Linting

.husky/pre-push, .storybook/main.ts, lib/components/forms/counter-input/index.stories.tsx, package-lock.json, package.json
This adds the ability to run user-interaction tests on components to verify they function as intended, along with a pre-push hook to verify commits did not break components.
=> Add Storybook Interaction Testing

.storybook/preview-head.html, lib/components/ui/dialog/index.stories.tsx, lib/components/ui/dialog/index.tsx
- adds test for dialog component
- adds documentation for dialog component
- adds Libre Franklin import to storybook
=> Create Dialog Tests/Documentation

lib/components/ui/input/index.stories.tsx
added shadcn input component to storybook docs
=> added shadcn input component to storybook docs

lib/__tests__/utils.test.ts, lib/actions/__tests__/actions-utils.test.ts, lib/actions/actions-utils.ts, lib/utils.ts
Adds some basic tests to make sure these functions work as intended, and prevent server actions from leaking out in environments they aren't supposed to.
=> Add Tests for actions-utils.ts and utils.ts

app/page.tsx
=> Remove Snowverlay from home page

app/page.tsx, lib/components/stand-form/__tests__/validate.test.ts, lib/components/stand-form/form.tsx, lib/components/stand-form/tabs.tsx, lib/components/stand-form/validate.ts, lib/components/ui/chart/index.tsx, lib/components/ui/label/index.tsx
=> Form validation errors

lib/components/stand-form/form.tsx, lib/components/stand-form/tabs.tsx, lib/components/stand-form/validate.ts, lib/components/ui/label/index.tsx
Add team and match number, change CSS so it looks nicer
=> Team and match number

next/.env.production, next/app/auth/callback/route.ts, next/lib/components/structural/navbar/sidebar.tsx, next/next.config.js
=> drew hotfixes 9/20

apps/analytics-server/.dockerignore, apps/analytics-server/.gitignore, apps/analytics-server/Dockerfile, apps/analytics-server/__init__.py, apps/analytics-server/app/api/__init__.py, apps/analytics-server/app/api/spr/controller.py, apps/analytics-server/app/api/spr/router.py, apps/analytics-server/app/api/spr/service.py, apps/analytics-server/app/api/tba_ingest/controller.py, apps/analytics-server/app/api/tba_ingest/router.py, apps/analytics-server/app/api/tba_ingest/service.py, apps/analytics-server/main.py, apps/analytics-server/package.json, apps/analytics-server/requirements.txt, compose.yaml
Creates a [FastAPI](https://fastapi.tiangolo.com) web server so we can leverage the benefits of numpy and other beneficial packages.
- Implements TBA webhook handler
- Adds layout for future SPR handling
=> Instantiating a basic analytics server that can handle TBA webhooks

apps/web/app/(sidebar)/layout.tsx, apps/web/app/(sidebar)/scout/components/AutoForm.tsx, apps/web/app/(sidebar)/scout/components/localStorage.ts, apps/web/app/(sidebar)/scout/components/utils.ts, apps/web/lib/utils.ts
Add auto saving of form to local storage while scouting matches
=> Add local saving

apps/web/app/(sidebar)/analysis/components/TeamDataTable.tsx, apps/web/app/(sidebar)/layout.tsx
Fixed the scrolling when the entire page would scroll rather than just the table
=> fixed the scrolling on the new scouting website

apps/web/lib/auth/utils.ts
Adds handling to get avalanche members nicknames if not member of YETI server
=> add avalanche

apps/web/app/(error)/error/page.tsx, apps/web/app/(sidebar)/analysis/actions/team-data.ts, apps/web/app/(sidebar)/scout/actions/teamsInMatch.ts, apps/web/app/(sidebar)/scout/form/FormHeader.tsx, apps/web/app/(sidebar)/scout/form/FormLayout.tsx, apps/web/app/(sidebar)/scout/form/FormNavigation.tsx, apps/web/app/(sidebar)/scout/form/FormProgress.tsx, apps/web/app/(sidebar)/scout/form/FormProvider.tsx, apps/web/app/(sidebar)/scout/form/steps/AutoPeriod.tsx, apps/web/app/(sidebar)/scout/form/steps/Endgame.tsx, apps/web/app/(sidebar)/scout/form/steps/MatchDetail.tsx, apps/web/app/(sidebar)/scout/form/steps/Miscellaneous.tsx, apps/web/app/(sidebar)/scout/form/steps/TeleopPeriod.tsx, apps/web/app/(sidebar)/scout/form/ui/CoralInput.tsx, apps/web/app/(sidebar)/scout/page.tsx, apps/web/lib/auth/auth.ts, apps/web/lib/auth/utils.ts
Add descriptions to error page, and more descriptive error handling
=> Linting + made error page more descriptive

apps/web/app/(sidebar)/admin/teams/page.tsx, apps/web/app/(sidebar)/admin/tools/page.tsx, apps/web/app/(sidebar)/analysis/page.tsx, apps/web/app/(sidebar)/scout/actions/submitForm.ts, apps/web/app/(sidebar)/scout/form/FormProvider.tsx, apps/web/app/(sidebar)/scout/layout.tsx, apps/web/app/(sidebar)/scout/page.tsx, apps/web/app/page.tsx, apps/web/components/app-sidebar/AppSidebar.tsx, apps/web/components/devtools/DevTools.tsx, apps/web/lib/auth/auth.ts, apps/web/lib/auth/utils.ts, apps/web/lib/database/schema.ts
Improvements:
- Made checking user role a bit easier with `checkSession` function
- Automatically log in user if they have an existing session, bypass discord login prompt
=> Auth updates

apps/web/lib/database/drizzle/0003_flashy_diamondback.sql, apps/web/lib/database/drizzle/meta/0003_snapshot.json, apps/web/lib/database/drizzle/meta/_journal.json, apps/web/lib/database/schema.ts, apps/web/package.json, pnpm-lock.yaml
This should hopefully prevent us from getting duplicate submissions in the future...
=> fix: add unique index to stand form

packages/yeti-blue-sdk/src/client/modules/matches.ts, packages/yeti-blue-sdk/src/client/yetiBlue.ts, packages/yeti-blue-sdk/src/schemas/event.ts, packages/yeti-blue-sdk/src/schemas/match.ts
created a new resource to get matches with the event using the eventKey API.
=> feat: add matches for event

packages/yeti-blue-sdk/src/client/modules/__tests__/matches.test.ts, packages/yeti-blue-sdk/src/schemas/match.ts
This PR:
- Adds test file for matches resource
- Formats and removes transform in match schema
=> chore: add tests for matches

packages/yeti-blue-sdk/src/client/modules/rankings.ts, packages/yeti-blue-sdk/src/schemas/rankings.ts
Adds the regional pool ranking query to the rankings resource as well as schema.
=> feat: add regional pool ranking query

packages/yeti-blue-sdk/README.md, packages/yeti-blue-sdk/src/client/modules/matches.ts
Introduce a new method to fetch a match by its key, enhancing the functionality of the MatchesResource class.
=> feat: add matchByKey method to MatchesResource class

apps/yeti-blue-sandbox/src/lib/client.ts, packages/yeti-blue-sdk/src/client/modules/media.ts, packages/yeti-blue-sdk/src/client/yetiBlue.ts, packages/yeti-blue-sdk/src/schemas/index.ts, packages/yeti-blue-sdk/src/schemas/media.ts, packages/yeti-blue-sdk/src/schemas/types.ts
adds queries to get media from blueAlliance
=> feat: media queries

apps/yeti-blue-sandbox/src/lib/client.ts, packages/yeti-blue-sdk/src/client/modules/rankings.ts, packages/yeti-blue-sdk/src/schemas/rankings.ts
Introduce a new feature to retrieve event rankings using the specified event key. Update the API key handling and enhance the documentation for clarity.
=> feat: event rankings package

apps/web/app/(sidebar)/admin/coverage/page.tsx, apps/web/app/(sidebar)/analysis/components/DataTable.tsx, apps/web/app/(sidebar)/layout.tsx, apps/web/lib/data/admin/coverage.ts, apps/web/lib/data/auth.ts, apps/web/lib/database/database.ts
Adds interface for being able to determine which matches are missing forms from the data.
=> feat: auditing of team-match coverage

compose.yaml
Removed the analytics-server stuff from `compose.yaml`
=> removed analytics server from compose

apps/web/components.json, packages/ui/components.json, packages/ui/src/styles/globals.css
Just changed the neutral scale into grayscale for tailwind. That's it.
=> tailwind grayscale for neutral colors

apps/web/.env.example
Added stuff to the .env.example file to make it easier to set up an .env.local file.
=> Example env.local File

package.json
Introduce new commands to run the scouting website and manage attendance, enhancing the development workflow.
=> Add commands for scouting and attendance development

apps/basecamp/src/bot/bot.commands.ts, apps/basecamp/src/data/attendance/attendance.service.spec.ts, apps/basecamp/src/data/attendance/attendance.service.ts, apps/basecamp/src/data/outreach/outreach.service.spec.ts, apps/basecamp/src/main.ts
- Added "attendance-leaderboard" command for top 5 users with the highest attendance. Logic very similar/nearly identical to outreach leaderboard.
- Added a getTopMembersByHours method to get the top users with there attendance.
=> Attendance leaderboard and unit tests for leaderboard

apps/web/app/page.tsx, apps/web/components/snowfall/snowfall.tsx, apps/web/package.json, pnpm-lock.yaml
added snow on the homepage!
closes #267
=> feat: snowfall animation 
